[tool.poetry]
name = "pydantic-bigquery"
version = "0.1.0"
description = ""
authors = ["Michael Mok <pmmmwh@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.13"
pydantic = "^2.6.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
